name: Android CI

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Download NDK
      run: echo y|"$ANDROID_SDK_ROOT/tools/bin/sdkmanager" --install "ndk;22.0.7026061"
      shell: bash
    - name: NDK build with command-line
      run: |
        cd xposeddetector/src/main
        "$ANDROID_SDK_ROOT/ndk/22.0.7026061/ndk-build" xposed_detector
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Grant execute permission for gradlew
      if: matrix.os != 'windows-latest'
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew aR --info || echo Build FAILED
    - name: Upload ndkBuild info
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-artifact
        path: xposeddetector/.cxx/
